FIX: doing my best to fix the failings of NPM and Node. Installing commander and setting NODE_PATH

diff --git a/install b/install
--- a/install
+++ b/install
@@ -183,7 +183,16 @@ if [ $? -ne 0 ]; then
 	>&2 echo "npm command is Not in the path.  Catastrophic failure in install script."
 fi
 npm install -g chalk
+pushd ~
+npm install commander@2.20.0
+npm install chalk
+popd
 
+echo export NODE_PATH=`npm root -g` >> .bashrc
+if [ $? -ne 0 ]; then
+	>&2 echo ' '
+	>&2 echo "npm command is Not in the path.  Catastrophic failure in install script."
+fi
 
 ###-------------------
 
